// 模具管理系统数据文件
// 此文件存储系统所有数据，可在不同电脑间共享
// 数据格式：window.__SOURCE_DATA__ 对象包含所有数据模块

window.__SOURCE_DATA__ = {
  "molds": [
    {
      "code": "FZ-MJ-24001",
      "name": "SC3E 喷漆装饰件B（备模）",
      "spec": "550*600*729",
      "weight": "1445",
      "machine": "注塑机",
      "machineNo": "HT380T",
      "supplier": "百瑞",
      "cavities": 1,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 119721,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-10-20",
      "notes": "",
      "id": "ms4a4lui0y2sz",
      "createdAt": "2026-07-28T06:33:11.322Z"
    },
    {
      "code": "FZ-MJ-23002",
      "name": "SC3E 喷漆装饰件A（备模）",
      "spec": "600*600*674",
      "weight": "1483",
      "machine": "注塑机",
      "machineNo": "HT320T",
      "supplier": "佰瑞",
      "cavities": 1,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 158932,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2023-08-11",
      "notes": "",
      "id": "ms4dhcofkq94w",
      "createdAt": "2026-07-28T08:07:04.815Z"
    },
    {
      "code": "FZ-MJ-24002",
      "name": "XC90_后左右壳体_RL/RR",
      "spec": "690*697*970",
      "weight": "2380",
      "machine": "注塑机",
      "machineNo": "HT380T",
      "supplier": "ODN模具中心",
      "cavities": 2,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 230440,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-11-16",
      "notes": "",
      "id": "ms4dnc23y46i3",
      "createdAt": "2026-07-28T08:11:43.947Z"
    },
    {
      "code": "FZ-MJ-24003",
      "name": "C121_MCM_壳体_C",
      "spec": "510*700*691",
      "weight": "1655",
      "machine": "注塑机",
      "machineNo": "HT380T",
      "supplier": "象山宁越",
      "cavities": 1,
      "moldType": "单色注塑",
      "lifetime": 500000,
      "shots": 200310,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-12-26",
      "notes": "",
      "id": "ms4doysiwjd31",
      "createdAt": "2026-07-28T08:13:00.066Z"
    },
    {
      "code": "FZ-MJ-24004",
      "name": "C121_MCM_主叶片1_CLCR",
      "spec": "360*630*401",
      "weight": "541",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "象山宁越",
      "cavities": 2,
      "moldType": "单色注塑",
      "lifetime": 500000,
      "shots": 35863,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-12-26",
      "notes": "",
      "id": "ms4ds2uhoauif",
      "createdAt": "2026-07-28T08:15:25.289Z"
    },
    {
      "code": "FZ-MJ-24005",
      "name": "C121_MCM_主叶片2_CLCR",
      "spec": "440*450*421",
      "weight": "540",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "象山宁越",
      "cavities": 2,
      "moldType": "单色注塑",
      "lifetime": 500000,
      "shots": 36426,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-12-26",
      "notes": "",
      "id": "ms4dv0coy0vnk",
      "createdAt": "2026-07-28T08:17:42.024Z"
    },
    {
      "code": "FZ-MJ-24007",
      "name": "C121_MCM_主叶片支架连杆12_LHRH",
      "spec": "450*650*436",
      "weight": "826",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "象山宁越",
      "cavities": 13,
      "moldType": "单色注塑",
      "lifetime": 500000,
      "shots": 37117,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-12-26",
      "notes": "",
      "id": "ms4fvs5lwts1l",
      "createdAt": "2026-07-28T09:14:17.289Z"
    },
    {
      "code": "FZ-MJ-24008",
      "name": "C121_MCM_次叶片123456_CLCR",
      "spec": "500*430*356",
      "weight": "490",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "象山宁越",
      "cavities": 11,
      "moldType": "单色注塑",
      "lifetime": 500000,
      "shots": 2534,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-12-26",
      "notes": "",
      "id": "ms4fxas5ik2ud",
      "createdAt": "2026-07-28T09:15:28.085Z"
    },
    {
      "code": "FZ-MJ-24009",
      "name": "C121_MCM_次叶片支架连杆12_CLCRLHRH",
      "spec": "460*600*431",
      "weight": "820",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "象山宁越",
      "cavities": 10,
      "moldType": "单色注塑",
      "lifetime": 500000,
      "shots": 3554,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-12-26",
      "notes": "",
      "id": "ms4fz5fxdphfi",
      "createdAt": "2026-07-28T09:16:54.477Z"
    },
    {
      "code": "FZ-MJ-24011",
      "name": "C121_MCM_壳体_LHRH",
      "spec": "600*1050*729",
      "weight": "2315",
      "machine": "注塑机",
      "machineNo": "HT380T",
      "supplier": "象山宁越",
      "cavities": 2,
      "moldType": "单色注塑",
      "lifetime": 500000,
      "shots": 103570,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-12-26",
      "notes": "",
      "id": "ms5o0i2zf1smf",
      "createdAt": "2026-07-29T05:49:40.619Z"
    },
    {
      "code": "FZ-MJ-24012",
      "name": "C121_MCM_主叶片1.3_LHRH",
      "spec": "460*670*451",
      "weight": "972",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "象山宁越",
      "cavities": 4,
      "moldType": "单色注塑",
      "lifetime": 500000,
      "shots": 36042,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-12-26",
      "notes": "",
      "id": "ms5qri5b7vk39",
      "createdAt": "2026-07-29T07:06:39.647Z"
    },
    {
      "code": "FZ-MJ-24013",
      "name": "C121_MCM_次叶片12345_LHRH",
      "spec": "470*600*381",
      "weight": "700",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "象山宁越",
      "cavities": 10,
      "moldType": "单色注塑",
      "lifetime": 500000,
      "shots": 38516,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-12-26",
      "notes": "",
      "id": "ms5qt6mw0glbb",
      "createdAt": "2026-07-29T07:07:58.040Z"
    },
    {
      "code": "FZ-MJ-24014",
      "name": "C121_MCM_主叶片2_LHRH",
      "spec": "560*360*391",
      "weight": "470",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "象山宁越",
      "cavities": 2,
      "moldType": "单色注塑",
      "lifetime": 500000,
      "shots": 43996,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2024-12-26",
      "notes": "",
      "id": "ms5qv4i2u0ver",
      "createdAt": "2026-07-29T07:09:28.586Z"
    },
    {
      "code": "FZ-MJ-25001",
      "name": "V206 侧转向手柄底座_894",
      "spec": "650*800*686",
      "weight": "2574",
      "machine": "注塑机",
      "machineNo": "HT380T",
      "supplier": "圣宝利",
      "cavities": 4,
      "moldType": "单色模具",
      "lifetime": 1000000,
      "shots": 107800,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-04-03",
      "notes": "",
      "id": "ms5qwl4j4ib2e",
      "createdAt": "2026-07-29T07:10:36.787Z"
    },
    {
      "code": "FZ-MJ-23001",
      "name": "SC3E-喷漆装饰件B",
      "spec": "550*600*729",
      "weight": "1445",
      "machine": "注塑机",
      "machineNo": "HT380T",
      "supplier": "佰瑞",
      "cavities": 1,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 78545,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2023-08-11",
      "notes": "",
      "id": "ms5r2rztfsvdm",
      "createdAt": "2026-07-29T07:15:25.625Z"
    },
    {
      "code": "FZ-MJ-25002",
      "name": "V206 后转向手柄底座_894",
      "spec": "600*750*531",
      "weight": "1650",
      "machine": "注塑机",
      "machineNo": "HT380T",
      "supplier": "盛立",
      "cavities": 4,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 116000,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-04-03",
      "notes": "",
      "id": "ms5r4sv44infl",
      "createdAt": "2026-07-29T07:17:00.064Z"
    },
    {
      "code": "FZ-MJ-250010",
      "name": "F2X/U_左右导流片_CTR",
      "spec": "600*600*568",
      "weight": "1293",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "ODN模具中心",
      "cavities": 12,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 20099,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-09-26",
      "notes": "",
      "id": "ms5r6ivw7pwap",
      "createdAt": "2026-07-29T07:18:20.444Z"
    },
    {
      "code": "FZ-MJ-25012",
      "name": "F2X/U_拨钮_CTR",
      "spec": "650*500*564.5",
      "weight": "1039",
      "machine": "注塑机",
      "machineNo": "HT320T",
      "supplier": "ODN模具中心",
      "cavities": 8,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 8914,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-09-26",
      "notes": "",
      "id": "ms5r85k8dtf9m",
      "createdAt": "2026-07-29T07:19:36.488Z"
    },
    {
      "code": "FZ-MJ-25013",
      "name": "F2X/U_主叶片1.3_OL/OR",
      "spec": "640*600*568",
      "weight": "1325",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "ODN模具中心",
      "cavities": 12,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 11853,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-09-26",
      "notes": "",
      "id": "ms5r9utjmj91i",
      "createdAt": "2026-07-29T07:20:55.879Z"
    },
    {
      "code": "FZ-MJ-25014",
      "name": "F2X/U_主叶片2_OL/OR",
      "spec": "450*810*561",
      "weight": "1250",
      "machine": "注塑机",
      "machineNo": "HT320T",
      "supplier": "ODN模具中心",
      "cavities": 8,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 4300,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-09-26",
      "notes": "",
      "id": "ms5rbglfw75p6",
      "createdAt": "2026-07-29T07:22:10.755Z"
    },
    {
      "code": "FZ-MJ-25015",
      "name": "F2X/U_拨钮_OL/OR",
      "spec": "600*1000*568",
      "weight": "2130",
      "machine": "注塑机",
      "machineNo": "HT320T",
      "supplier": "ODN模具中心",
      "cavities": 8,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 13854,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-09-26",
      "notes": "",
      "id": "ms5ssrcn6akd0",
      "createdAt": "2026-07-29T08:03:37.463Z"
    },
    {
      "code": "FZ-MJ-25006",
      "name": "D13 喷漆装饰件-新",
      "spec": "121*293*92",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "ZE-3600",
      "supplier": "佰瑞",
      "cavities": 1,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 83631,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-08-20",
      "notes": "",
      "id": "ms5svw97yxtef",
      "createdAt": "2026-07-29T08:06:03.787Z"
    },
    {
      "code": "FZ-MJ-25016",
      "name": "ST2 左右装饰件-喷漆",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT160T",
      "supplier": "佰瑞",
      "cavities": 2,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 69468,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-09-30",
      "notes": "",
      "id": "ms5t0imxlvtla",
      "createdAt": "2026-07-29T08:09:39.417Z"
    },
    {
      "code": "FZ-MJ-25017",
      "name": "LH-装饰亮条",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT160T",
      "supplier": "协柯",
      "cavities": 2,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 0,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-10-11",
      "notes": "",
      "id": "ms5t1qw8v7i5o",
      "createdAt": "2026-07-29T08:10:36.776Z"
    },
    {
      "code": "FZ-MJ-25011",
      "name": "F2X/U_主叶片2_CTR",
      "spec": "640X940X587",
      "weight": "2462",
      "machine": "注塑机",
      "machineNo": "HT320T",
      "supplier": "ODN模具中心",
      "cavities": 8,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 14168,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-09-26",
      "notes": "",
      "id": "ms6xtts009bqd",
      "createdAt": "2026-07-30T03:12:11.520Z"
    },
    {
      "code": "FZ-MJ-25018",
      "name": "FL扬声器灯-165-166-铭牌-素材",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT160T",
      "supplier": "理实",
      "cavities": 8,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 3200,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-11-20",
      "notes": "",
      "id": "ms78lb5ucyove",
      "createdAt": "2026-07-30T08:13:29.922Z"
    },
    {
      "code": "FZ-MJ-25019",
      "name": "FL扬声器灯-167-铭牌-素材",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT160T",
      "supplier": "理实",
      "cavities": 8,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 4120,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-11-20",
      "notes": "",
      "id": "ms78n6qq0i26u",
      "createdAt": "2026-07-30T08:14:57.506Z"
    },
    {
      "code": "FZ-MJ-25008",
      "name": "W01B 左侧出风口内圈亮条-SL/SR",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "理实",
      "cavities": 2,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 0,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-09-04",
      "notes": "",
      "id": "ms78q5apuu5a3",
      "createdAt": "2026-07-30T08:17:15.601Z"
    },
    {
      "code": "FZ-MJ-26003",
      "name": "KP31后排出风口面板",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "理实",
      "cavities": 1,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 0,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "潘彦达",
      "madeDate": "2026-03-19",
      "notes": "",
      "id": "ms78ruzpeopeq",
      "createdAt": "2026-07-30T08:18:35.557Z"
    },
    {
      "code": "FZ-MJ-26001",
      "name": "T26哑光电镀喷漆件",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT380T",
      "supplier": "佰瑞",
      "cavities": 1,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 0,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "潘彦达",
      "madeDate": "2026-02-01",
      "notes": "",
      "id": "ms8bm0g35gwem",
      "createdAt": "2026-07-31T02:25:47.716Z"
    },
    {
      "code": "FZ-MJ-26002",
      "name": "新X11反光碗L/R-素材",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT160T",
      "supplier": "理实",
      "cavities": 4,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 53680,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2026-03-10",
      "notes": "",
      "id": "ms8bnfsj58oyb",
      "createdAt": "2026-07-31T02:26:54.259Z"
    },
    {
      "code": "FZ-MJ-26004",
      "name": "理想W05 左B柱出风口拨扭",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "富强鑫160T",
      "supplier": "佰瑞",
      "cavities": 2,
      "moldType": "双色注塑",
      "lifetime": 1000000,
      "shots": 0,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "潘彦达",
      "madeDate": "2026-05-15",
      "notes": "",
      "id": "ms8bpgbny3gl4",
      "createdAt": "2026-07-31T02:28:28.259Z"
    },
    {
      "code": "FZ-MJ-26005",
      "name": "X83副司机侧拨钮-素材",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT160T",
      "supplier": "理实",
      "cavities": 4,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 0,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2026-07-06",
      "notes": "",
      "id": "ms8br116bjvuc",
      "createdAt": "2026-07-31T02:29:41.754Z"
    },
    {
      "code": "FZ-MJ-26006",
      "name": "X83司机侧拨钮-素材",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT160T",
      "supplier": "理实",
      "cavities": 4,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 0,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2026-07-06",
      "notes": "",
      "id": "ms8bsf520rtkp",
      "createdAt": "2026-07-31T02:30:46.694Z"
    },
    {
      "code": "FZ-MJ-25004",
      "name": "673D中面框素材",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "ZE-3600",
      "supplier": "理实",
      "cavities": 1,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 117393,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-06-04",
      "notes": "",
      "id": "ms8btxqqflu2n",
      "createdAt": "2026-07-31T02:31:57.458Z"
    },
    {
      "code": "FZ-MJ-25005",
      "name": "673D左喷漆面板素材",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT250T",
      "supplier": "理实",
      "cavities": 2,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 76619,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-06-04",
      "notes": "",
      "id": "ms8buyeu5rtbj",
      "createdAt": "2026-07-31T02:32:44.982Z"
    },
    {
      "code": "FZ-MJ-25006",
      "name": "G28后中扶手 杯托电镀件-素材",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT320T",
      "supplier": "晶美科技",
      "cavities": 2,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 101728,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-08-25",
      "notes": "",
      "id": "ms8bwubhp2afp",
      "createdAt": "2026-07-31T02:34:12.989Z"
    },
    {
      "code": "FZ-MJ-25007",
      "name": "G18后中扶手 杯托电镀件-素材",
      "spec": "",
      "weight": "",
      "machine": "注塑机",
      "machineNo": "HT160T",
      "supplier": "晶美科技",
      "cavities": 1,
      "moldType": "单色注塑",
      "lifetime": 1000000,
      "shots": 92303,
      "status": "正常",
      "workshop": "注塑车间",
      "stage": "量产",
      "owner": "杨民涛",
      "madeDate": "2025-08-25",
      "notes": "",
      "id": "ms8bxxxkeqd4s",
      "createdAt": "2026-07-31T02:35:04.328Z"
    }
  ],
  "fixtures": [
    {
      "code": "FZ-GZ-001",
      "name": "C673装饰件焊接工装",
      "spec": "600*400*430mm",
      "weight": "",
      "machine": "伺服热铆焊接机",
      "machineNo": "FZ-HJ-001",
      "supplier": "苏州华卓自动化设备有限公司",
      "cavities": 1,
      "moldType": "热铆焊接",
      "lifetime": 500000,
      "shots": 0,
      "status": "正常",
      "workshop": "装配车间",
      "owner": "钟意",
      "madeDate": "2023-11-04",
      "notes": "",
      "id": "mto1bpw9w7bmv",
      "createdAt": "2026-09-05T07:01:52.473Z",
      "_targetType": "fixture"
    },
    {
      "code": "FZ-GZ-002",
      "name": "C236装饰件焊接工装",
      "spec": "700*350*520mm",
      "weight": "",
      "machine": "伺服热铆焊接机",
      "machineNo": "FZ-HJ-001",
      "supplier": "苏州锦铎自动化科技有限公司",
      "cavities": 1,
      "moldType": "热铆焊接",
      "lifetime": 500000,
      "shots": 0,
      "status": "正常",
      "workshop": "装配车间",
      "owner": "钟意",
      "madeDate": "2024-02-04",
      "notes": "",
      "id": "mto1gvcg1556d",
      "createdAt": "2026-09-05T07:05:52.816Z",
      "_targetType": "fixture"
    },
    {
      "code": "FZ-GZ-003",
      "name": "HXHA装饰件焊接工装",
      "spec": "600*350*400mm",
      "weight": "",
      "machine": "伺服热铆焊接机",
      "machineNo": "FZ-HJ-003",
      "supplier": "苏州华卓自动化设备有限公司",
      "cavities": 1,
      "moldType": "热铆焊接",
      "lifetime": 500000,
      "shots": 0,
      "status": "正常",
      "workshop": "装配车间",
      "owner": "钟意",
      "madeDate": "2024-04-04",
      "notes": "",
      "id": "mto1w2fch86sg",
      "createdAt": "2026-09-05T07:17:41.832Z",
      "_targetType": "fixture"
    },
    {
      "code": "FZ-GZ-006",
      "name": "SC3E装饰件焊接工装",
      "spec": "660*350*430mm",
      "weight": "",
      "machine": "伺服热铆焊接机",
      "machineNo": "FZ-HJ-002/FZ-HJ-004",
      "supplier": "苏州锦铎自动化科技有限公司",
      "cavities": 1,
      "moldType": "热铆焊接",
      "lifetime": 500000,
      "shots": 0,
      "status": "正常",
      "workshop": "装配车间",
      "owner": "钟意",
      "madeDate": "2024-08-05",
      "notes": "",
      "id": "mto1ytjj14ebx",
      "createdAt": "2026-09-05T07:19:50.287Z",
      "_targetType": "fixture"
    },
    {
      "code": "FZ-GZ-007",
      "name": "D13装饰件焊接工装",
      "spec": "660*350*400mm",
      "weight": "",
      "machine": "伺服热铆焊接机",
      "machineNo": "FZ-HJ-002",
      "supplier": "苏州锦铎自动化科技有限公司",
      "cavities": 1,
      "moldType": "热铆焊接",
      "lifetime": 500000,
      "shots": 0,
      "status": "正常",
      "workshop": "装配车间",
      "owner": "钟意",
      "madeDate": "2025-11-05",
      "notes": "",
      "id": "mto214x2nmqmi",
      "createdAt": "2026-09-05T07:21:38.342Z",
      "_targetType": "fixture"
    },
    {
      "code": "FZ-GZ-008",
      "name": "ST2装饰件焊接工装",
      "spec": "660*350*480mm",
      "weight": "",
      "machine": "伺服热铆焊接机",
      "machineNo": "FZ-HJ-004",
      "supplier": "苏州锦铎自动化科技有限公司",
      "cavities": 1,
      "moldType": "热铆焊接",
      "lifetime": 500000,
      "shots": 0,
      "status": "正常",
      "workshop": "装配车间",
      "owner": "钟意",
      "madeDate": "2025-12-05",
      "notes": "",
      "id": "mto24fie1j8to",
      "createdAt": "2026-09-05T07:24:12.038Z",
      "_targetType": "fixture"
    },
    {
      "code": "FZ-GZ-009",
      "name": "T26装饰件焊接工装",
      "spec": "660*350*430mm",
      "weight": "",
      "machine": "伺服热铆焊接机",
      "machineNo": "FZ-HJ-002",
      "supplier": "苏州锦铎自动化科技有限公司",
      "cavities": 1,
      "moldType": "热铆焊接",
      "lifetime": 500000,
      "shots": 0,
      "status": "正常",
      "workshop": "装配车间",
      "owner": "钟意",
      "madeDate": "2026-04-05",
      "notes": "",
      "id": "mto27mcmwv3qu",
      "createdAt": "2026-09-05T07:26:40.870Z",
      "_targetType": "fixture"
    }
  ],
  "maintenance": [
    {
      "moldId": "ms5t0imxlvtla",
      "date": "2026-07-24",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "ms8hcis6yku6u"
    },
    {
      "moldId": "ms4ds2uhoauif",
      "date": "2026-08-01",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msahhjcsnskut"
    },
    {
      "moldId": "ms4fz5fxdphfi",
      "date": "2026-07-28",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "顶针*2，滑块维修",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msahqbcrtj139"
    },
    {
      "moldId": "ms8btxqqflu2n",
      "date": "2026-08-04",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msehjexdwt22c"
    },
    {
      "moldId": "ms4a4lui0y2sz",
      "date": "2026-07-08",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "更换斜顶*2",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfp9dtl84pzw"
    },
    {
      "moldId": "ms4dhcofkq94w",
      "date": "2026-07-08",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfp9z0ccpjnh"
    },
    {
      "moldId": "ms4dnc23y46i3",
      "date": "2026-07-19",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfpb4uc8vpv6"
    },
    {
      "moldId": "ms4doysiwjd31",
      "date": "2026-03-27",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfpbrz01qe6o"
    },
    {
      "moldId": "ms4doysiwjd31",
      "date": "2026-06-26",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfpdnhrmcph8"
    },
    {
      "moldId": "ms4dv0coy0vnk",
      "date": "2026-03-18",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfpej7vxm2p9"
    },
    {
      "moldId": "ms4dv0coy0vnk",
      "date": "2026-06-12",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfpeyynjatms"
    },
    {
      "moldId": "ms4fvs5lwts1l",
      "date": "2026-03-22",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfph1lqabq1e"
    },
    {
      "moldId": "ms4fvs5lwts1l",
      "date": "2026-06-26",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfphisykd6y0"
    },
    {
      "moldId": "ms4fxas5ik2ud",
      "date": "2026-03-18",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfqbiy4dfb38"
    },
    {
      "moldId": "ms4fxas5ik2ud",
      "date": "2026-06-26",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfqbwm0g7r88"
    },
    {
      "moldId": "ms5o0i2zf1smf",
      "date": "2026-03-12",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfqco1f9g7q1"
    },
    {
      "moldId": "ms5o0i2zf1smf",
      "date": "2026-06-10",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfqd047idec2"
    },
    {
      "moldId": "ms5qri5b7vk39",
      "date": "2026-03-21",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfqdp0skl2v5"
    },
    {
      "moldId": "ms5qri5b7vk39",
      "date": "2026-06-18",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfqe8oric7qz"
    },
    {
      "moldId": "ms5qt6mw0glbb",
      "date": "2026-03-11",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msftmm88ab2rx"
    },
    {
      "moldId": "ms5qt6mw0glbb",
      "date": "2026-06-11",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msftn1yw2rpsb"
    },
    {
      "moldId": "ms5qv4i2u0ver",
      "date": "2026-03-19",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msfttwcmnpuo9"
    },
    {
      "moldId": "ms5qv4i2u0ver",
      "date": "2026-06-25",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msftv1gzd61e0"
    },
    {
      "moldId": "ms5qwl4j4ib2e",
      "date": "2026-07-10",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msftvx1qypb5t"
    },
    {
      "moldId": "ms5r2rztfsvdm",
      "date": "2026-07-08",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msftx3yv4ngq8"
    },
    {
      "moldId": "ms5r4sv44infl",
      "date": "2026-07-10",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgr0vb0s4vnf"
    },
    {
      "moldId": "ms5r6ivw7pwap",
      "date": "2026-05-15",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgr1ju9pk4e4"
    },
    {
      "moldId": "ms5r85k8dtf9m",
      "date": "2026-07-10",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgr2r8p1sxng"
    },
    {
      "moldId": "ms5r9utjmj91i",
      "date": "2026-05-15",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgr3gbg8j28u"
    },
    {
      "moldId": "ms5rbglfw75p6",
      "date": "2026-05-15",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgr43eryt3st"
    },
    {
      "moldId": "ms5ssrcn6akd0",
      "date": "2026-05-15",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgr4wp3t233e"
    },
    {
      "moldId": "ms5svw97yxtef",
      "date": "2026-03-17",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgr5qmwe3k83"
    },
    {
      "moldId": "ms5svw97yxtef",
      "date": "2026-06-19",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgr667v73w1p"
    },
    {
      "moldId": "ms5t1qw8v7i5o",
      "date": "2026-07-20",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgr8t6u7wg1o"
    },
    {
      "moldId": "ms6xtts009bqd",
      "date": "2026-05-15",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgrka5wyn6xe"
    },
    {
      "moldId": "ms78lb5ucyove",
      "date": "2026-08-05",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "增加涂层",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgrnjgnqo60o"
    },
    {
      "moldId": "ms78n6qq0i26u",
      "date": "2026-08-05",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "增加涂层",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgrp61n3gzuc"
    },
    {
      "moldId": "ms8buyeu5rtbj",
      "date": "2026-02-18",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgrt9ae7031x"
    },
    {
      "moldId": "ms8buyeu5rtbj",
      "date": "2026-05-23",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgrtrzh8zqyn"
    },
    {
      "moldId": "ms8bwubhp2afp",
      "date": "2026-07-31",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgrwbgw8scde"
    },
    {
      "moldId": "ms8bxxxkeqd4s",
      "date": "2026-03-28",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgrxo0lvdzw4"
    },
    {
      "moldId": "ms8bxxxkeqd4s",
      "date": "2026-06-16",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgry58mw37j2"
    },
    {
      "moldId": "ms8br116bjvuc",
      "date": "2026-07-27",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgrzusdza1q0"
    },
    {
      "moldId": "ms8bsf520rtkp",
      "date": "2026-07-27",
      "type": "二级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "更换顶针*3",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgs0w3gfupvj"
    },
    {
      "moldId": "ms8bnfsj58oyb",
      "date": "2026-03-06",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgvu15kn8b7l"
    },
    {
      "moldId": "ms8bnfsj58oyb",
      "date": "2026-06-26",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgvunfsswv5c"
    },
    {
      "moldId": "ms8bpgbny3gl4",
      "date": "2026-05-15",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgvwzhcy4l8l"
    },
    {
      "moldId": "ms8bpgbny3gl4",
      "date": "2026-08-06",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msgvxeebvj40p"
    },
    {
      "moldId": "ms5rbglfw75p6",
      "date": "2026-08-07",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msidsoqfj2us2"
    },
    {
      "moldId": "ms8bm0g35gwem",
      "date": "2026-08-07",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msjpcuy1hvqvb"
    },
    {
      "moldId": "ms78ruzpeopeq",
      "date": "2026-07-29",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msjpd98cbitm0"
    },
    {
      "moldId": "ms78q5apuu5a3",
      "date": "2026-07-08",
      "type": "三级保养",
      "cost": 0,
      "content": "三级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msjpe7q0evsbg"
    },
    {
      "moldId": "ms5ssrcn6akd0",
      "date": "2026-08-17",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "mswmtlmj27bnt"
    },
    {
      "moldId": "ms6xtts009bqd",
      "date": "2026-08-15",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "更换热流道感温线",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "mswmu28nmmgo1"
    },
    {
      "moldId": "ms5r9utjmj91i",
      "date": "2026-08-17",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "mswmubl0wvgow"
    },
    {
      "moldId": "ms5r6ivw7pwap",
      "date": "2026-08-18",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msxz724ny2wry"
    },
    {
      "moldId": "ms8btxqqflu2n",
      "date": "2026-08-18",
      "type": "二级保养",
      "cost": 0,
      "content": "二级保养内容",
      "parts": "",
      "worker": "杨民涛",
      "result": "正常",
      "notes": "",
      "id": "msxz7cvo6qsaz"
    }
  ],
  "repairs": [
    {
      "moldId": "ms4dv0coy0vnk",
      "date": "2026-07-31",
      "level": "一般",
      "cost": 0,
      "downtime": 12,
      "fault": "镶针断裂",
      "content": "更换镶针",
      "cause": "滑块镶针困气，导致镶针烧断",
      "parts": "镶针*2",
      "worker": "杨民涛",
      "notes": "",
      "id": "msgsl4cg9to3u"
    },
    {
      "moldId": "ms8bwubhp2afp",
      "date": "2026-07-31",
      "level": "一般",
      "cost": 0,
      "downtime": 0,
      "fault": "产品飞边卷边",
      "content": "烧焊，抛光",
      "cause": "疲劳磨损",
      "parts": "",
      "worker": "杨民涛",
      "notes": "",
      "id": "msgspufeaqtup"
    },
    {
      "moldId": "ms6xtts009bqd",
      "date": "2026-08-15",
      "level": "一般",
      "cost": 0,
      "downtime": 0,
      "fault": "流道第十四个点报警",
      "content": "更换感温线",
      "cause": "感温线故障",
      "parts": "更换感温线",
      "worker": "杨民涛",
      "notes": "",
      "id": "mswn0yiqp8zd9"
    },
    {
      "moldId": "ms78lb5ucyove",
      "date": "2026-08-05",
      "level": "一般",
      "cost": 0,
      "downtime": 0,
      "fault": "产品凹坑多",
      "content": "增加涂层",
      "cause": "空气灰尘容易粘模具表面",
      "parts": "",
      "worker": "杨民涛",
      "notes": "",
      "id": "mswn5u5y3vpr9"
    },
    {
      "moldId": "ms78n6qq0i26u",
      "date": "2026-08-05",
      "level": "一般",
      "cost": 0,
      "downtime": 0,
      "fault": "产品表面凹坑",
      "content": "增加涂层",
      "cause": "空气灰尘容易粘模具表面",
      "parts": "",
      "worker": "杨民涛",
      "notes": "",
      "id": "mswn6n2x922nh"
    },
    {
      "moldId": "ms78lb5ucyove",
      "date": "2026-08-18",
      "level": "一般",
      "cost": 500,
      "downtime": 0,
      "fault": "热流道故障",
      "content": "更换感温线",
      "cause": "操作不当",
      "parts": "",
      "worker": "杨民涛",
      "notes": "",
      "id": "msxz8up4wbiaq"
    },
    {
      "moldId": "ms4a4lui0y2sz",
      "date": "2026-07-20",
      "level": "严重",
      "cost": 0,
      "downtime": 0,
      "fault": "斜顶卡死",
      "content": "更换斜顶",
      "cause": "模具结构原因",
      "parts": "斜顶 X2",
      "worker": "杨民涛",
      "notes": "",
      "id": "mt26ezeu2264p"
    },
    {
      "moldId": "ms4fz5fxdphfi",
      "date": "2026-07-28",
      "level": "严重",
      "cost": 0,
      "downtime": 0,
      "fault": "滑块卡死，顶针卡死",
      "content": "更换顶针",
      "cause": "模具生锈",
      "parts": "顶针X1",
      "worker": "杨民涛",
      "notes": "",
      "id": "mt26hg9863wak"
    }
  ],
  "usage": [
    {
      "moldId": "ms4doysiwjd31",
      "date": "2026-08-03",
      "machine": "注塑机",
      "shots": 3644,
      "duration": 56,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "msehfbxsjpgp0"
    },
    {
      "moldId": "ms4fz5fxdphfi",
      "date": "2026-08-04",
      "machine": "注塑机",
      "shots": 3554,
      "duration": 42,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "msfnet7ea8469"
    },
    {
      "moldId": "ms4dv0coy0vnk",
      "date": "2026-07-30",
      "machine": "注塑机",
      "shots": 3612,
      "duration": 42,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "msfngv39pi2x6"
    },
    {
      "moldId": "ms8bxxxkeqd4s",
      "date": "2026-07-27",
      "machine": "注塑机",
      "shots": 4277,
      "duration": 48,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "msfnj82gppv81"
    },
    {
      "moldId": "ms5t0imxlvtla",
      "date": "2026-08-03",
      "machine": "注塑机",
      "shots": 16625,
      "duration": 158,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "msfnqt23umyoa"
    },
    {
      "moldId": "ms4a4lui0y2sz",
      "date": "2026-07-22",
      "machine": "注塑机",
      "shots": 5598,
      "duration": 71.5,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "msfntm5yqxkqq"
    },
    {
      "moldId": "ms4dhcofkq94w",
      "date": "2026-07-23",
      "machine": "注塑机",
      "shots": 6723,
      "duration": 84.5,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "msfnuqgp2zcxd"
    },
    {
      "moldId": "ms5o0i2zf1smf",
      "date": "2026-08-06",
      "machine": "注塑机",
      "shots": 3574,
      "duration": 60,
      "operator": "孙文敬",
      "notes": "",
      "id": "mswng31z061jw"
    },
    {
      "moldId": "ms8bxxxkeqd4s",
      "date": "2026-08-06",
      "machine": "注塑机",
      "shots": 5047,
      "duration": 67.5,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswni0425t7kk"
    },
    {
      "moldId": "ms5qv4i2u0ver",
      "date": "2026-08-08",
      "machine": "注塑机",
      "shots": 5128,
      "duration": 74.4,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswnkm3idoins"
    },
    {
      "moldId": "ms5qt6mw0glbb",
      "date": "2026-08-06",
      "machine": "注塑机",
      "shots": 3031,
      "duration": 31.5,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswnn92i1h04x"
    },
    {
      "moldId": "ms78n6qq0i26u",
      "date": "2026-08-07",
      "machine": "注塑机",
      "shots": 700,
      "duration": 10,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswnov0dfnr07"
    },
    {
      "moldId": "ms78n6qq0i26u",
      "date": "2026-08-14",
      "machine": "注塑机",
      "shots": 3420,
      "duration": 51,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswnput5kbn3v"
    },
    {
      "moldId": "ms78lb5ucyove",
      "date": "2026-08-12",
      "machine": "注塑机",
      "shots": 3200,
      "duration": 80,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswnr1q0hasxd"
    },
    {
      "moldId": "ms5svw97yxtef",
      "date": "2026-08-11",
      "machine": "注塑机",
      "shots": 8027,
      "duration": 80,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswns83t1jr40"
    },
    {
      "moldId": "ms5r85k8dtf9m",
      "date": "2026-08-08",
      "machine": "注塑机",
      "shots": 2514,
      "duration": 32,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswntgdkhucvf"
    },
    {
      "moldId": "ms4fxas5ik2ud",
      "date": "2026-08-11",
      "machine": "注塑机",
      "shots": 2534,
      "duration": 31,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswnuzpcvgcag"
    },
    {
      "moldId": "ms4dnc23y46i3",
      "date": "2026-08-15",
      "machine": "注塑机",
      "shots": 8143,
      "duration": 95,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswnw4snrdvmq"
    },
    {
      "moldId": "ms5ssrcn6akd0",
      "date": "2026-08-14",
      "machine": "注塑机",
      "shots": 4100,
      "duration": 51.5,
      "operator": "孙文敬",
      "notes": "批量生产",
      "id": "mswnyax7exeys"
    }
  ],
  "plans": [
    {
      "moldId": "ms5r2rztfsvdm",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-08",
      "content": "",
      "id": "ms5uedyajiyse"
    },
    {
      "moldId": "ms4a4lui0y2sz",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-08",
      "content": "",
      "id": "ms6wx9r2v60o9"
    },
    {
      "moldId": "ms4a4lui0y2sz",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-08",
      "content": "",
      "id": "ms6wyfl2sugus"
    },
    {
      "moldId": "ms5r2rztfsvdm",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-08",
      "content": "",
      "id": "ms6x0mpipl9ex"
    },
    {
      "moldId": "ms4dhcofkq94w",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-08",
      "content": "",
      "id": "ms6x19v6vydet"
    },
    {
      "moldId": "ms4dhcofkq94w",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-08",
      "content": "",
      "id": "ms6x3fdon90sr"
    },
    {
      "moldId": "ms4dnc23y46i3",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-19",
      "content": "",
      "id": "ms6x4lgd9bfz6"
    },
    {
      "moldId": "ms4dnc23y46i3",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-19",
      "content": "",
      "id": "ms6x5b9irsiam"
    },
    {
      "moldId": "ms5qwl4j4ib2e",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-10",
      "content": "",
      "id": "ms6x5vj2qm3uz"
    },
    {
      "moldId": "ms5qwl4j4ib2e",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-10",
      "content": "",
      "id": "ms6x65di43u7f"
    },
    {
      "moldId": "ms5r4sv44infl",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-10",
      "content": "",
      "id": "ms6xbn3tkl7o0"
    },
    {
      "moldId": "ms5r4sv44infl",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-10",
      "content": "",
      "id": "ms6xbyyku3r1b"
    },
    {
      "moldId": "ms5r85k8dtf9m",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-10",
      "content": "",
      "id": "ms6xdz6z36yjd"
    },
    {
      "moldId": "ms5r85k8dtf9m",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-10",
      "content": "",
      "id": "ms6xeekblih2b"
    },
    {
      "moldId": "ms5rbglfw75p6",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-08-07",
      "content": "",
      "id": "ms6xg96vrs6fe"
    },
    {
      "moldId": "ms5rbglfw75p6",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-05-15",
      "content": "",
      "id": "ms6xi4juch0nq"
    },
    {
      "moldId": "ms5ssrcn6akd0",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-08-17",
      "content": "",
      "id": "ms6xjelqq0ptp"
    },
    {
      "moldId": "ms5ssrcn6akd0",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-05-15",
      "content": "",
      "id": "ms6xk5wqxur7e"
    },
    {
      "moldId": "ms6xtts009bqd",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-08-15",
      "content": "",
      "id": "ms6xxpnvkk23r"
    },
    {
      "moldId": "ms6xtts009bqd",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-05-15",
      "content": "",
      "id": "ms6xywp6ss55w"
    },
    {
      "moldId": "ms5r9utjmj91i",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-08-17",
      "content": "",
      "id": "ms6xzu1uao8n6"
    },
    {
      "moldId": "ms5r9utjmj91i",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-05-15",
      "content": "",
      "id": "ms6y0jqz8kkej"
    },
    {
      "moldId": "ms5r6ivw7pwap",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-08-18",
      "content": "",
      "id": "ms6y3gr4uhwg5"
    },
    {
      "moldId": "ms5r6ivw7pwap",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-05-15",
      "content": "",
      "id": "ms6y3vkyaeefo"
    },
    {
      "moldId": "ms5t0imxlvtla",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-12",
      "content": "",
      "id": "ms6ygch2c8v0k"
    },
    {
      "moldId": "ms5t0imxlvtla",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-24",
      "content": "",
      "id": "ms6ygslae6hpd"
    },
    {
      "moldId": "ms8buyeu5rtbj",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-05-27",
      "content": "",
      "id": "ms8dv142p9pov"
    },
    {
      "moldId": "ms8buyeu5rtbj",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-05-27",
      "content": "",
      "id": "ms8dwaw6mtcax"
    },
    {
      "moldId": "ms8btxqqflu2n",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-08-18",
      "content": "",
      "id": "ms8h1s6th36d9"
    },
    {
      "moldId": "ms8btxqqflu2n",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-08-04",
      "content": "",
      "id": "ms8h2ridjt7l2"
    },
    {
      "moldId": "ms8bnfsj58oyb",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-26",
      "content": "",
      "id": "ms8h8wrzwjno7"
    },
    {
      "moldId": "ms8bnfsj58oyb",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-06",
      "content": "",
      "id": "ms8h9osm47eol"
    },
    {
      "moldId": "ms5t0imxlvtla",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-25",
      "content": "",
      "id": "ms8hb79jm70bs"
    },
    {
      "moldId": "ms5t0imxlvtla",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-24",
      "content": "",
      "id": "ms8hbrorcmyny"
    },
    {
      "moldId": "ms5svw97yxtef",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-19",
      "content": "",
      "id": "ms8hefoptmbtf"
    },
    {
      "moldId": "ms5svw97yxtef",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-17",
      "content": "",
      "id": "ms8hf0l2kh1fm"
    },
    {
      "moldId": "ms8bxxxkeqd4s",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-16",
      "content": "",
      "id": "ms8ihrcq9b34k"
    },
    {
      "moldId": "ms8bxxxkeqd4s",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-28",
      "content": "",
      "id": "ms8iiam56x706"
    },
    {
      "moldId": "ms8bwubhp2afp",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-31",
      "content": "",
      "id": "ms8jryjkrcnt0"
    },
    {
      "moldId": "ms8bwubhp2afp",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-31",
      "content": "",
      "id": "ms8jsje4woxu1"
    },
    {
      "moldId": "ms4doysiwjd31",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-26",
      "content": "",
      "id": "ms8jucfr3fwyi"
    },
    {
      "moldId": "ms4doysiwjd31",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-27",
      "content": "",
      "id": "ms8jureg5olm7"
    },
    {
      "moldId": "ms5o0i2zf1smf",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-10",
      "content": "",
      "id": "msah4y5a9hmu8"
    },
    {
      "moldId": "ms5o0i2zf1smf",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-12",
      "content": "",
      "id": "msah5p6arjrb1"
    },
    {
      "moldId": "ms4fvs5lwts1l",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-26",
      "content": "",
      "id": "msaha96q3y1xc"
    },
    {
      "moldId": "ms4fvs5lwts1l",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-22",
      "content": "",
      "id": "msahaqxjagutb"
    },
    {
      "moldId": "ms5qri5b7vk39",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-18",
      "content": "",
      "id": "msahboiqpgchj"
    },
    {
      "moldId": "ms5qri5b7vk39",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-21",
      "content": "",
      "id": "msahc0s1mhnao"
    },
    {
      "moldId": "ms4fxas5ik2ud",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-26",
      "content": "",
      "id": "msahesolf94pr"
    },
    {
      "moldId": "ms5qt6mw0glbb",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-11",
      "content": "",
      "id": "msahfdo4zau61"
    },
    {
      "moldId": "ms4ds2uhoauif",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-18",
      "content": "",
      "id": "msahgg6z5muof"
    },
    {
      "moldId": "ms4ds2uhoauif",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-08-01",
      "content": "",
      "id": "msahgucr71wp6"
    },
    {
      "moldId": "ms4dv0coy0vnk",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-12",
      "content": "",
      "id": "msahl810sj018"
    },
    {
      "moldId": "ms4dv0coy0vnk",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-18",
      "content": "",
      "id": "msahlq93ifr4v"
    },
    {
      "moldId": "ms4fz5fxdphfi",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-28",
      "content": "",
      "id": "msahnz1pgzuoz"
    },
    {
      "moldId": "ms4fz5fxdphfi",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-28",
      "content": "",
      "id": "msahorfnnormq"
    },
    {
      "moldId": "ms5qt6mw0glbb",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-11",
      "content": "",
      "id": "msfpz3o2zibga"
    },
    {
      "moldId": "ms4fxas5ik2ud",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-18",
      "content": "",
      "id": "msfq1vj50qjrm"
    },
    {
      "moldId": "ms5qv4i2u0ver",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-25",
      "content": "",
      "id": "msftsm5rewigb"
    },
    {
      "moldId": "ms5qv4i2u0ver",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-03-19",
      "content": "",
      "id": "msftswb7gcejx"
    },
    {
      "moldId": "ms5t1qw8v7i5o",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-20",
      "content": "",
      "id": "msgr810bvnzz5"
    },
    {
      "moldId": "ms5t1qw8v7i5o",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-20",
      "content": "",
      "id": "msgr8ahc1q88b"
    },
    {
      "moldId": "ms78lb5ucyove",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-08-05",
      "content": "",
      "id": "msgrmx0596a7k"
    },
    {
      "moldId": "ms78lb5ucyove",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-08-05",
      "content": "",
      "id": "msgrn6oy4ud16"
    },
    {
      "moldId": "ms78n6qq0i26u",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-08-05",
      "content": "",
      "id": "msgrnwq7jom1m"
    },
    {
      "moldId": "ms78n6qq0i26u",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-08-05",
      "content": "",
      "id": "msgro3bwr06be"
    },
    {
      "moldId": "ms8br116bjvuc",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-27",
      "content": "",
      "id": "msgrz2l96eife"
    },
    {
      "moldId": "ms8br116bjvuc",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-27",
      "content": "",
      "id": "msgrz8swectvg"
    },
    {
      "moldId": "ms8bsf520rtkp",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-27",
      "content": "",
      "id": "msgs07zgipi7i"
    },
    {
      "moldId": "ms8bsf520rtkp",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-07-27",
      "content": "",
      "id": "msgs0dsot8duh"
    },
    {
      "moldId": "ms8bpgbny3gl4",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-05-15",
      "content": "",
      "id": "msgvvu5vidxy0"
    },
    {
      "moldId": "ms8bpgbny3gl4",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-08-06",
      "content": "",
      "id": "msgvw8lvbzl70"
    },
    {
      "moldId": "ms78q5apuu5a3",
      "type": "三级保养",
      "intervalDays": 180,
      "shotInterval": 100000,
      "lastDate": "2026-07-08",
      "content": "",
      "id": "msgvyk2qoztwo"
    },
    {
      "moldId": "ms78q5apuu5a3",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 50000,
      "lastDate": "2026-06-10",
      "content": "",
      "id": "msgvz885oefch"
    },
    {
      "moldId": "mto1bpw9w7bmv",
      "targetType": "fixture",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 0,
      "lastDate": "2026-09-01",
      "content": "",
      "id": "mto57hi7qqvxn"
    },
    {
      "moldId": "mto1gvcg1556d",
      "targetType": "fixture",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 0,
      "lastDate": "2026-09-01",
      "content": "",
      "id": "mto583ewvy9aa"
    },
    {
      "moldId": "mto1w2fch86sg",
      "targetType": "fixture",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 0,
      "lastDate": "2026-09-01",
      "content": "",
      "id": "mto58a7zrn7bu"
    },
    {
      "moldId": "mto1ytjj14ebx",
      "targetType": "fixture",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 0,
      "lastDate": "2026-09-01",
      "content": "",
      "id": "mto58ikg1hhon"
    },
    {
      "moldId": "mto214x2nmqmi",
      "targetType": "fixture",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 0,
      "lastDate": "2026-09-01",
      "content": "",
      "id": "mto58sfzdnes9"
    },
    {
      "moldId": "mto24fie1j8to",
      "targetType": "fixture",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 0,
      "lastDate": "2026-09-01",
      "content": "",
      "id": "mto590db3rbo1"
    },
    {
      "moldId": "mto27mcmwv3qu",
      "targetType": "fixture",
      "type": "二级保养",
      "intervalDays": 90,
      "shotInterval": 0,
      "lastDate": "2026-09-01",
      "content": "",
      "id": "mto5971jhf5jv"
    },
    {
      "moldId": "mto1bpw9w7bmv",
      "targetType": "fixture",
      "type": "三级保养",
      "intervalDays": 365,
      "shotInterval": 0,
      "lastDate": "2025-12-31",
      "content": "",
      "id": "mto5a087sa4sd"
    },
    {
      "moldId": "mto1gvcg1556d",
      "targetType": "fixture",
      "type": "三级保养",
      "intervalDays": 365,
      "shotInterval": 0,
      "lastDate": "2025-12-31",
      "content": "",
      "id": "mto5b0hrjmqdw"
    },
    {
      "moldId": "mto1w2fch86sg",
      "targetType": "fixture",
      "type": "三级保养",
      "intervalDays": 365,
      "shotInterval": 0,
      "lastDate": "2025-12-31",
      "content": "",
      "id": "mto5bdf3mcf2u"
    },
    {
      "moldId": "mto1ytjj14ebx",
      "targetType": "fixture",
      "type": "三级保养",
      "intervalDays": 365,
      "shotInterval": 100000,
      "lastDate": "2025-12-31",
      "content": "",
      "id": "mto5br2gaynnf"
    },
    {
      "moldId": "mto214x2nmqmi",
      "targetType": "fixture",
      "type": "三级保养",
      "intervalDays": 365,
      "shotInterval": 0,
      "lastDate": "2025-12-31",
      "content": "",
      "id": "mto6oc7ob571z"
    },
    {
      "moldId": "mto24fie1j8to",
      "targetType": "fixture",
      "type": "三级保养",
      "intervalDays": 365,
      "shotInterval": 0,
      "lastDate": "2025-12-31",
      "content": "",
      "id": "mto6p750ubdzq"
    },
    {
      "moldId": "mto27mcmwv3qu",
      "targetType": "fixture",
      "type": "三级保养",
      "intervalDays": 365,
      "shotInterval": 0,
      "lastDate": "2025-12-31",
      "content": "",
      "id": "mto6puass7zb4"
    }
  ],
  "users": [
    {
      "id": "admin-default",
      "username": "admin",
      "password": "admin123",
      "fullname": "系统管理员",
      "role": "admin",
      "status": "active",
      "notes": "默认管理员账号",
      "createdAt": "2026-01-01T00:00:00.000Z",
      "lastLogin": "2026-09-05T10:10:06.610Z"
    },
    {
      "id": "ms467hqjnkk75",
      "username": "mintao.yang@fangsteering.com",
      "fullname": "杨民涛",
      "password": "123456",
      "role": "editor",
      "status": "active",
      "notes": "生产主管",
      "createdAt": "2026-07-28T04:43:27.499Z",
      "lastLogin": "2026-07-28T04:44:04.960Z"
    },
    {
      "id": "ms469cf3pj7ou",
      "username": "yanda.pan@fangsteering.com",
      "fullname": "潘彦达",
      "password": "123456",
      "role": "editor",
      "status": "active",
      "notes": "模具工程师",
      "createdAt": "2026-07-28T04:44:53.919Z",
      "lastLogin": null
    },
    {
      "id": "ms49fz0qzsd9k",
      "username": "yun.wang@fangsteering.com",
      "fullname": "王云",
      "password": "12345678",
      "role": "admin",
      "status": "active",
      "notes": "董事长",
      "createdAt": "2026-07-28T06:14:01.994Z",
      "lastLogin": null
    },
    {
      "id": "ms49ghy9b7wri",
      "username": "devin.liu@fangsteering.com",
      "fullname": "刘云霄",
      "password": "12345678",
      "role": "admin",
      "status": "active",
      "notes": "总经理",
      "createdAt": "2026-07-28T06:14:26.529Z",
      "lastLogin": null
    }
  ],
  "version": "1.2.0"
};